/*
 * HAL_I2C.h
 *
 *  Created on: 12 sept. 2022
 *      Author: morgan.venandy
 */

#ifndef HAL_HAL_I2C_HAL_I2C_H_
#define HAL_HAL_I2C_HAL_I2C_H_

#include <stdint.h>
#include "LLD_I2C.h"

typedef enum 
{
	E_SLAVE_READ_DATA_V,
	E_SLAVE_READ_DATA_A,
	E_SLAVE_READ_DATA_DOCK,
    E_SLAVE_READ_DATA_TIME_TO_MOW,
	E_SLAVE_READ_DATA_SONAR_FC,
	E_SLAVE_READ_DATA_SONAR_FL,
	E_SLAVE_READ_DATA_SONAR_FR,
	E_SLAVE_READ_DATA_GPS_LONG_MMSB,
	E_SLAVE_READ_DATA_GPS_LONG_MSB,
	E_SLAVE_READ_DATA_GPS_LONG_LSB,
	E_SLAVE_READ_DATA_GPS_LONG_LLSB,
	E_SLAVE_READ_DATA_GPS_LAT_MMSB,
	E_SLAVE_READ_DATA_GPS_LAT_MSB,
	E_SLAVE_READ_DATA_GPS_LAT_LSB,
	E_SLAVE_READ_DATA_GPS_LAT_LLSB,
    E_SLAVE_READ_DATA_LED_STATUS,
	
	E_SLAVE_READ_DATA_NUMBER
}E_SLAVE_READ_DATA;

void HAL_I2C_Init(lld_i2c_callback_t pf_callback);
uint8_t HAL_I2C_IsI2cBusy(void);

#endif /* HAL_HAL_I2C_HAL_I2C_H_ */
